package capitulo10;
// Este programa contém um erro e não compila.
//public class ThrowsDemo {
//    static void throwsOne() throws IllegalAccessException{
//        System.out.println("Dentro do ThrowsOne");
//        throw new IllegalAccessException("demo");
//    }
//
//    public static void main(String[] args) {
//        try {
//            throwsOne();
//        }catch (IllegalAccessException e){
//            System.out.println("Caught " + e);
//        }
//    }
//}
